### ISSUE TITLE
email tidak bisa diawali huruf kecil

### ISSUE THREAD

**Issue by gslayer0** [2018-PemrogramanWeb-B/tugas7-fp-cupu_berkualitas#1]
![email tidak bisa diawali huruf kecil](https://user-images.githubusercontent.com/37019764/50212650-23b88980-03ae-11e9-85a9-a349d1de7426.PNG)

**Comment by cyber12drago** [comment]
silahkan baca http://fmukti.blogspot.com/2012/02/berpengaruhkah-huruf-besar-huruf-kecil.html . 

dan saat didatabase hasilnya akan seperti ini
![db](https://user-images.githubusercontent.com/36811855/50213949-aabb3100-03b1-11e9-8b9f-890082a5f2a9.jpg)

Terimakasih

**Comment by gslayer0** [comment]
Tentu ini akan membingungkan user. mohon diperbaiki. terimakasih
