### ISSUE TITLE
Tidak terjadi apa apa setelah login

### ISSUE THREAD

**Issue by gslayer0** [2018-PemrogramanWeb-B/tugas7-fp-cupu_berkualitas#2]
![tidak terjadi apa apa setelah login](https://user-images.githubusercontent.com/37019764/50212699-40ed5800-03ae-11e9-9827-0e7fcc72036d.PNG)

**Comment by cluster777** [comment]
sudah menjalankan dbcreate.php?
atau jika sudah bisa memberi detail lebih

**Comment by gslayer0** [comment]
Untuk db telah dibuat. Mohon sertakan prosedur installasi supaya tester dapat lebih mudah melakukan pengujian.

**Comment by cluster777** [comment]
login page dari kami tidak ada masalah, untuk prosedur instalasi telah dibuat sebelumnya
