### ISSUE TITLE
Tidak otomatis redirect ke login page jika username/password salah

### ISSUE THREAD

**Issue by Iotatfan** [2018-PemrogramanWeb-B/tugas7-fp-cupu_berkualitas#3]
![screenshot 90](https://user-images.githubusercontent.com/42773954/50215181-cd9b1480-03b4-11e9-93fa-cee4e8614799.png)

**Comment by cyber12drago** [comment]
Coba cek lagi...Mungkin kamu yg salah. Jangan lupa dbcreate
